//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CodeNamesClientSide.Properties {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CodeNamesClientSide.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Accept Request.
        /// </summary>
        public static string AcceptFriendRequestButton {
            get {
                return ResourceManager.GetString("AcceptFriendRequestButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cancel.
        /// </summary>
        public static string CancelButton {
            get {
                return ResourceManager.GetString("CancelButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Exit Game.
        /// </summary>
        public static string CloseGameButton {
            get {
                return ResourceManager.GetString("CloseGameButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The room code has been copied to cllipboard.
        /// </summary>
        public static string Copy_RoomCode_Message {
            get {
                return ResourceManager.GetString("Copy_RoomCode_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Room code copied.
        /// </summary>
        public static string Copy_RoomCode_Title {
            get {
                return ResourceManager.GetString("Copy_RoomCode_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Create Game.
        /// </summary>
        public static string CreateGameButton {
            get {
                return ResourceManager.GetString("CreateGameButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Decline Request.
        /// </summary>
        public static string DeclineFriendRequestButton {
            get {
                return ResourceManager.GetString("DeclineFriendRequestButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Delete Friend.
        /// </summary>
        public static string DeleteFriendButton {
            get {
                return ResourceManager.GetString("DeleteFriendButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Email.
        /// </summary>
        public static string EmailLabel {
            get {
                return ResourceManager.GetString("EmailLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Connection to the server could not be established.
        /// </summary>
        public static string Exception_NoConnection_Message {
            get {
                return ResourceManager.GetString("Exception_NoConnection_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error.
        /// </summary>
        public static string Exception_NoConnection_Title {
            get {
                return ResourceManager.GetString("Exception_NoConnection_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Font Size.
        /// </summary>
        public static string FontSizeSelector {
            get {
                return ResourceManager.GetString("FontSizeSelector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Options.
        /// </summary>
        public static string FriendListSettingsOptLabel {
            get {
                return ResourceManager.GetString("FriendListSettingsOptLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Friend.
        /// </summary>
        public static string FriendNicknameLabel {
            get {
                return ResourceManager.GetString("FriendNicknameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Friend Requests.
        /// </summary>
        public static string FriendRequestsButton {
            get {
                return ResourceManager.GetString("FriendRequestsButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Warning.
        /// </summary>
        public static string GeneralWarning {
            get {
                return ResourceManager.GetString("GeneralWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Go Back.
        /// </summary>
        public static string GoBackButton {
            get {
                return ResourceManager.GetString("GoBackButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Invite to a game.
        /// </summary>
        public static string InviteGameButton {
            get {
                return ResourceManager.GetString("InviteGameButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Join Game.
        /// </summary>
        public static string JoinGameButton {
            get {
                return ResourceManager.GetString("JoinGameButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Unable to join the room because it is full or the game has already started.
        /// </summary>
        public static string JoinRoom_CantJoin_Message {
            get {
                return ResourceManager.GetString("JoinRoom_CantJoin_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a You need to enter the code.
        /// </summary>
        public static string JoinRoom_NoCode_Message {
            get {
                return ResourceManager.GetString("JoinRoom_NoCode_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Language.
        /// </summary>
        public static string LanguageSelector {
            get {
                return ResourceManager.GetString("LanguageSelector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Log In.
        /// </summary>
        public static string LogInButton {
            get {
                return ResourceManager.GetString("LogInButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Log In.
        /// </summary>
        public static string LogInLabel {
            get {
                return ResourceManager.GetString("LogInLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Music On.
        /// </summary>
        public static string MusicSelector {
            get {
                return ResourceManager.GetString("MusicSelector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Music Volume.
        /// </summary>
        public static string MusicVolumeSelector {
            get {
                return ResourceManager.GetString("MusicVolumeSelector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a My Friend List.
        /// </summary>
        public static string MyFriendListButton {
            get {
                return ResourceManager.GetString("MyFriendListButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nickname.
        /// </summary>
        public static string NicknameLabel {
            get {
                return ResourceManager.GetString("NicknameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Confirmation Password.
        /// </summary>
        public static string PasswordConfirmationLabel {
            get {
                return ResourceManager.GetString("PasswordConfirmationLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Password.
        /// </summary>
        public static string PasswordLabel {
            get {
                return ResourceManager.GetString("PasswordLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Play as Guest.
        /// </summary>
        public static string PlayAsGuestButton {
            get {
                return ResourceManager.GetString("PlayAsGuestButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Search.
        /// </summary>
        public static string SearchButton {
            get {
                return ResourceManager.GetString("SearchButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Search People.
        /// </summary>
        public static string SearchPeopleButton {
            get {
                return ResourceManager.GetString("SearchPeopleButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Add Friend.
        /// </summary>
        public static string SendFriendRequestButton {
            get {
                return ResourceManager.GetString("SendFriendRequestButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Settings.
        /// </summary>
        public static string SettingsButton {
            get {
                return ResourceManager.GetString("SettingsButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sign Up.
        /// </summary>
        public static string SignUpButton {
            get {
                return ResourceManager.GetString("SignUpButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sign Up into CodeNames.
        /// </summary>
        public static string SignUpCodeNamesLabel {
            get {
                return ResourceManager.GetString("SignUpCodeNamesLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Social.
        /// </summary>
        public static string SocialButton {
            get {
                return ResourceManager.GetString("SocialButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Status.
        /// </summary>
        public static string StatusLabel {
            get {
                return ResourceManager.GetString("StatusLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Update Email.
        /// </summary>
        public static string UpdateEmailButton {
            get {
                return ResourceManager.GetString("UpdateEmailButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Update Password.
        /// </summary>
        public static string UpdatePasswordButton {
            get {
                return ResourceManager.GetString("UpdatePasswordButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a View Profile.
        /// </summary>
        public static string ViewProfileButton {
            get {
                return ResourceManager.GetString("ViewProfileButton", resourceCulture);
            }
        }
    }
}
